### ISSUE TITLE
Rename coding challenge

### ISSUE THREAD

**Issue by drgibson** [ColdSteamyShower/Ayden-Best-Vue-Proj#1]
When you get a moment, would you rename the coding challenge.

We have had an issue with candidate in the past plagiarizing the coding challenge. Thanks.

**Comment by ColdSteamyShower** [comment]
Hi Darius,

Just renamed the project as requested. Let me know if there are any
specific changes that I should make to the file names.

https://github.com/ColdSteamyShower/Ayden-Best-Vue-Proj

**Comment by drgibson** [comment]
Thanks for updating the name!
